<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Bucket Bunga Satin Pink',
                'slug' => 'bucket-bunga-satin-pink',
                'description' => 'Bucket bunga satin yang indah dan elegan, cocok untuk hadiah spesial kepada orang tersayang. Dibuat dengan bahan berkualitas tinggi dan desain yang menarik. Sempurna untuk berbagai acara seperti ulang tahun, anniversary, atau sebagai ungkapan kasih sayang.',
                'short_description' => 'Bucket bunga satin yang indah dan elegan, cocok untuk hadiah spesial kepada orang tersayang.',
                'price' => 350000,
                'sale_price' => 250000,
                'sku' => 'PRD-SAT-001',
                'stock_quantity' => 25,
                'category' => 'satin',
                'status' => 'active',
                'featured' => true,
                'images' => ['images/product/12.jpg'],
                'weight' => 500,
                'dimensions' => '25cm x 30cm x 15cm',
                'meta_title' => 'Bucket Bunga Satin Pink - Hadiah Romantis Terbaik',
                'meta_description' => 'Bucket bunga satin pink elegan untuk hadiah spesial. Kualitas premium dengan harga terjangkau.',
            ],
            [
                'name' => 'Bucket Satin with Glitter',
                'slug' => 'bucket-satin-with-glitter',
                'description' => 'Bucket bunga satin dengan hiasan glitter yang berkilau, memberikan kesan mewah dan elegan. Cocok untuk acara-acara istimewa yang membutuhkan sentuhan glamour. Dibuat dengan perhatian detail tinggi untuk memberikan pengalaman terbaik.',
                'short_description' => 'Bucket bunga satin dengan hiasan glitter yang berkilau, memberikan kesan mewah dan elegan.',
                'price' => 470000,
                'sale_price' => 370000,
                'sku' => 'PRD-GLI-001',
                'stock_quantity' => 18,
                'category' => 'glitter',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/16.jpg'],
                'weight' => 600,
                'dimensions' => '30cm x 35cm x 18cm',
                'meta_title' => 'Bucket Satin Glitter - Kemewahan dalam Genggaman',
                'meta_description' => 'Bucket satin dengan glitter berkilau untuk acara istimewa. Desain mewah dan elegan.',
            ],
            [
                'name' => 'Bucket Kawat Bulu',
                'slug' => 'bucket-kawat-bulu',
                'description' => 'Bunga kawat bulu yang unik dan tahan lama, cocok untuk dekorasi atau hadiah yang berkesan. Desain yang kreatif dan bahan yang berkualitas membuat produk ini menjadi pilihan favorit. Tahan lama dan mudah perawatan.',
                'short_description' => 'Bunga kawat bulu yang unik dan tahan lama, cocok untuk dekorasi atau hadiah yang berkesan.',
                'price' => 450000,
                'sale_price' => 270000,
                'sku' => 'PRD-KAW-001',
                'stock_quantity' => 32,
                'category' => 'kawat',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/6.jpg'],
                'weight' => 400,
                'dimensions' => '25cm x 30cm x 15cm',
                'meta_title' => 'Bucket Kawat Bulu - Dekorasi Unik dan Tahan Lama',
                'meta_description' => 'Bucket kawat bulu kreatif untuk dekorasi rumah. Unik, tahan lama, dan mudah perawatan.',
            ],
            [
                'name' => 'Bucket Money Special',
                'slug' => 'bucket-money-special',
                'description' => 'Bucket money yang kreatif dan unik, hadiah yang sempurna untuk berbagai acara spesial. Desain yang inovatif dan kualitas premium menjadikan produk ini pilihan terbaik untuk memberikan kesan yang tak terlupakan.',
                'short_description' => 'Bucket money yang kreatif dan unik, hadiah yang sempurna untuk berbagai acara spesial.',
                'price' => 470000,
                'sale_price' => 310000,
                'sku' => 'PRD-MON-001',
                'stock_quantity' => 15,
                'category' => 'money',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/18.jpg'],
                'weight' => 550,
                'dimensions' => '30cm x 35cm x 20cm',
                'meta_title' => 'Bucket Money Special - Hadiah Kreatif dan Berkesan',
                'meta_description' => 'Bucket money kreatif untuk hadiah spesial. Desain inovatif dengan kualitas premium.',
            ],
            [
                'name' => 'Bucket Bunga Premium Rose',
                'slug' => 'bucket-bunga-premium-rose',
                'description' => 'Bucket bunga berkualitas tinggi dengan desain yang menarik dan elegan. Menggunakan bunga mawar premium yang dipilih khusus untuk memberikan kesan romantis dan mewah.',
                'short_description' => 'Bucket bunga berkualitas tinggi dengan desain yang menarik dan elegan.',
                'price' => 320000,
                'sale_price' => null,
                'sku' => 'PRD-SAT-002',
                'stock_quantity' => 20,
                'category' => 'satin',
                'status' => 'active',
                'featured' => false,
                'images' => ['assets/images/product/13.jpg'],
                'weight' => 480,
                'dimensions' => '25cm x 30cm x 15cm',
                'meta_title' => 'Bucket Bunga Premium Rose - Kemewahan Alami',
                'meta_description' => 'Bucket bunga mawar premium untuk hadiah romantis. Kualitas terbaik dengan harga terjangkau.',
            ],
            [
                'name' => 'Bucket Satin Elegant White',
                'slug' => 'bucket-satin-elegant-white',
                'description' => 'Bucket bunga satin putih yang elegan dan bersih, cocok untuk acara pernikahan atau perayaan khusus. Desain minimalis namun tetap memukau.',
                'short_description' => 'Bucket bunga satin putih yang elegan dan bersih, cocok untuk acara pernikahan.',
                'price' => 280000,
                'sale_price' => null,
                'sku' => 'PRD-SAT-003',
                'stock_quantity' => 30,
                'category' => 'satin',
                'status' => 'active',
                'featured' => false,
                'images' => ['assets/images/product/14.jpg'],
                'weight' => 450,
                'dimensions' => '25cm x 30cm x 15cm',
                'meta_title' => 'Bucket Satin Elegant White - Kesucian dalam Keindahan',
                'meta_description' => 'Bucket satin putih elegan untuk pernikahan dan acara khusus. Desain minimalis yang memukau.',
            ],
            [
                'name' => 'Bucket Glitter Gold Luxury',
                'slug' => 'bucket-glitter-gold-luxury',
                'description' => 'Bucket bunga dengan glitter emas yang mewah, memberikan kesan glamour dan eksklusif. Sempurna untuk acara-acara penting dan momen bersejarah.',
                'short_description' => 'Bucket bunga dengan glitter emas yang mewah, memberikan kesan glamour dan eksklusif.',
                'price' => 520000,
                'sale_price' => 420000,
                'sku' => 'PRD-GLI-002',
                'stock_quantity' => 12,
                'category' => 'glitter',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/15.jpg'],
                'weight' => 650,
                'dimensions' => '32cm x 38cm x 20cm',
                'meta_title' => 'Bucket Glitter Gold Luxury - Kemewahan Emas Berkilau',
                'meta_description' => 'Bucket glitter emas mewah untuk acara eksklusif. Glamour dan berkesan.',
            ],
            [
                'name' => 'Bucket Kawat Artistic',
                'slug' => 'bucket-kawat-artistic',
                'description' => 'Bucket kawat dengan desain artistik yang unik, menggabungkan seni dan keindahan dalam satu produk. Cocok untuk pecinta seni dan dekorasi modern.',
                'short_description' => 'Bucket kawat dengan desain artistik yang unik, menggabungkan seni dan keindahan.',
                'price' => 380000,
                'sale_price' => 290000,
                'sku' => 'PRD-KAW-002',
                'stock_quantity' => 22,
                'category' => 'kawat',
                'status' => 'active',
                'featured' => false,
                'images' => ['assets/images/product/17.jpg'],
                'weight' => 420,
                'dimensions' => '28cm x 32cm x 16cm',
                'meta_title' => 'Bucket Kawat Artistic - Seni dalam Dekorasi',
                'meta_description' => 'Bucket kawat artistik untuk dekorasi modern. Unik dan penuh karakter.',
            ],
            [
                'name' => 'Bucket Money Celebration',
                'slug' => 'bucket-money-celebration',
                'description' => 'Bucket money khusus untuk perayaan dan ucapan selamat. Desain yang ceria dan penuh makna untuk berbagai momen bahagia.',
                'short_description' => 'Bucket money khusus untuk perayaan dan ucapan selamat.',
                'price' => 350000,
                'sale_price' => null,
                'sku' => 'PRD-MON-002',
                'stock_quantity' => 18,
                'category' => 'money',
                'status' => 'active',
                'featured' => false,
                'images' => ['assets/images/product/19.jpg'],
                'weight' => 500,
                'dimensions' => '28cm x 33cm x 18cm',
                'meta_title' => 'Bucket Money Celebration - Perayaan yang Berkesan',
                'meta_description' => 'Bucket money untuk perayaan spesial. Ceria dan penuh makna.',
            ],
            [
                'name' => 'Bucket Custom Personalized',
                'slug' => 'bucket-custom-personalized',
                'description' => 'Bucket bunga custom yang dapat dipersonalisasi sesuai keinginan. Cocok untuk hadiah yang benar-benar personal dan berkesan.',
                'short_description' => 'Bucket bunga custom yang dapat dipersonalisasi sesuai keinginan.',
                'price' => 450000,
                'sale_price' => 380000,
                'sku' => 'PRD-CUS-001',
                'stock_quantity' => 10,
                'category' => 'custom',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/20.jpg'],
                'weight' => 520,
                'dimensions' => 'Custom sesuai permintaan',
                'meta_title' => 'Bucket Custom Personalized - Hadiah Personal Terbaik',
                'meta_description' => 'Bucket custom yang dipersonalisasi untuk hadiah istimewa. Unik dan berkesan.',
            ],
            [
                'name' => 'Bucket Special Anniversary',
                'slug' => 'bucket-special-anniversary',
                'description' => 'Bucket spesial untuk perayaan anniversary dengan desain romantis dan elegan. Dibuat khusus untuk momen-momen berharga dalam hubungan.',
                'short_description' => 'Bucket spesial untuk perayaan anniversary dengan desain romantis dan elegan.',
                'price' => 480000,
                'sale_price' => 400000,
                'sku' => 'PRD-SPE-001',
                'stock_quantity' => 14,
                'category' => 'special',
                'status' => 'active',
                'featured' => true,
                'images' => ['assets/images/product/21.jpg'],
                'weight' => 580,
                'dimensions' => '30cm x 35cm x 18cm',
                'meta_title' => 'Bucket Special Anniversary - Cinta yang Abadi',
                'meta_description' => 'Bucket spesial anniversary untuk momen romantis. Elegan dan berkesan.',
            ],
            [
                'name' => 'Bucket Satin Pastel Collection',
                'slug' => 'bucket-satin-pastel-collection',
                'description' => 'Koleksi bucket satin dengan warna-warna pastel yang lembut dan menenangkan. Cocok untuk berbagai suasana dan acara.',
                'short_description' => 'Koleksi bucket satin dengan warna-warna pastel yang lembut dan menenangkan.',
                'price' => 300000,
                'sale_price' => null,
                'sku' => 'PRD-SAT-004',
                'stock_quantity' => 25,
                'category' => 'satin',
                'status' => 'active',
                'featured' => false,
                'images' => ['assets/images/product/22.jpg'],
                'weight' => 460,
                'dimensions' => '25cm x 30cm x 15cm',
                'meta_title' => 'Bucket Satin Pastel - Kelembutan dalam Warna',
                'meta_description' => 'Bucket satin pastel untuk suasana lembut dan menenangkan.',
            ],
        ];

        foreach ($products as $productData) {
            Product::create($productData);
        }
    }
}